import Head from "next/head";
import { useState } from "react";

import ImagePreview from "../components/ImagePreview";

export default function Home({ items }) {
  const [search, setSearch] = useState('');
  const [photos, setPhotos] = useState(items);

  return (
    <div className='container'>
      <Head>
        <title>NASA Image Gallery</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <h1>Hello!</h1>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://images-api.nasa.gov/search?media_type=image"
  );
  const preview = await res.json();
  const items = await preview.collection.items;

  return {
    props: { items },
  };
}
